import React from "react";

const SampleMyRecipes = [
  {
    recipeOwnerId: "user789",
    recipeNameId: "vegetableBiryani987",
    recipeName: "Vegetable Biryani",
    ingredients: {
      BasmatiRice: "1 cup, soaked",
      MixedVegetables: "1 cup (carrots, peas, beans)",
      Onion: "1, thinly sliced",
      Tomatoes: "2, chopped",
      GingerGarlicPaste: "1 tbsp",
      BiryaniMasala: "2 tsp",
      CuminSeeds: "1 tsp",
      CinnamonStick: "1 inch",
      Cloves: "3",
      Cardamom: "2 pods",
      BayLeaves: "2",
      CashewNuts: "10",
      Ghee: "2 tbsp",
      CorianderLeaves: "for garnish",
      Salt: "to taste",
      Water: "2 cups",
    },
    steps: [
      "Heat ghee in a pan and add cumin seeds, cinnamon stick, cloves, cardamom, and bay leaves.",
      "Add sliced onions and sauté until golden brown.",
      "Add ginger-garlic paste and chopped tomatoes. Cook until tomatoes are soft.",
      "Add mixed vegetables, biryani masala, and soaked rice. Sauté for 2 minutes.",
      "Transfer the mixture to a rice cooker, add water, and cook until rice is done.",
      "Garnish with fried cashew nuts and coriander leaves. Serve hot.",
    ],
  },
  {
    recipeOwnerId: "user606",
    recipeNameId: "dalTadka707",
    recipeName: "Dal Tadka",
    ingredients: {
      "YellowLentils (Toor Dal)": "1 cup, washed",
      Onion: "1, finely chopped",
      Tomatoes: "2, chopped",
      GreenChilies: "2, chopped",
      "Ginger-GarlicPaste": "1 tbsp",
      CuminSeeds: "1 tsp",
      MustardSeeds: "1/2 tsp",
      "Asafoetida (Hing)": "a pinch",
      TurmericPowder: "1/2 tsp",
      RedChiliPowder: "1/2 tsp",
      GaramMasala: "1/2 tsp",
      CurryLeaves: "a few",
      CookingOil: "2 tbsp",
      Salt: "to taste",
      FreshCoriander: "for garnish",
    },
    steps: [
      "Boil the lentils with turmeric powder and salt until soft. Mash them slightly.",
      "In a separate pan, heat oil, add cumin seeds, mustard seeds, hing, and curry leaves.",
      "Add chopped onions, green chilies, and ginger-garlic paste. Sauté until onions are golden brown.",
      "Add chopped tomatoes, red chili powder, and garam masala. Cook until tomatoes are soft.",
      "Mix the cooked lentils with the tempering mixture. Adjust the consistency by adding water if needed.",
      "Garnish with fresh coriander leaves and serve hot with rice or roti.",
    ],
  },
  {
    recipeOwnerId: "user999",
    recipeNameId: "tandooriChicken1010",
    recipeName: "Tandoori Chicken",
    ingredients: {
      Chicken: "500 gm, cut into pieces",
      Yogurt: "1/2 cup",
      "Ginger-GarlicPaste": "2 tbsp",
      RedChiliPowder: "1 tbsp",
      TurmericPowder: "1/2 tsp",
      GaramMasala: "1 tsp",
      LemonJuice: "2 tbsp",
      Salt: "to taste",
      CookingOil: "2 tbsp",
      TandooriMasala: "2 tbsp",
      FreshCoriander: "for garnish",
    },
    steps: [
      "In a bowl, mix yogurt, ginger-garlic paste, red chili powder, turmeric powder, garam masala, lemon juice, and salt to make the marinade.",
      "Marinate the chicken in the mixture and refrigerate for at least 2 hours.",
      "Preheat the oven to 200°C. Thread the chicken onto skewers.",
      "Brush with oil and sprinkle tandoori masala over the chicken.",
      "Bake for 25-30 minutes or until the chicken is fully cooked and has a charred appearance.",
      "Garnish with fresh coriander leaves and serve hot.",
    ],
  },
];

export default SampleMyRecipes;
