import React from "react";

const SampleRecipes = [
  {
    recipeOwnerId: "user123",
    recipeNameId: "chickenCurry123",
    recipeName: "Chicken Curry",
    ingredients: {
      Chicken: "500 gm, cut into pieces",
      Onion: "2, finely chopped",
      Tomatoes: "2, pureed",
      Ginger: "1 inch, grated",
      Garlic: "4 cloves, minced",
      GreenChilies: "2, chopped",
      CorianderPowder: "1 tbsp",
      CuminPowder: "1 tsp",
      TurmericPowder: "1/2 tsp",
      RedChiliPowder: "1 tsp",
      GaramMasala: "1 tsp",
      BayLeaves: "2",
      CinnamonStick: "1 inch",
      Cloves: "3",
      Cardamom: "2 pods",
      Salt: "to taste",
      CookingOil: "3 tbsp",
      FreshCoriander: "for garnish",
    },
    steps: [
      "Heat oil in a pan over medium heat. Add bay leaves, cinnamon stick, cloves, and cardamom.",
      "Add chopped onions and sauté until golden brown.",
      "Add grated ginger, minced garlic, and chopped green chilies. Sauté for 2 minutes.",
      "Add pureed tomatoes and cook until the oil separates from the masala.",
      "Add coriander powder, cumin powder, turmeric powder, red chili powder, and salt. Mix well.",
      "Add chicken pieces and cook until they are browned on all sides.",
      "Add water as needed, cover the pan, and let it simmer until the chicken is cooked through.",
      "Sprinkle garam masala and garnish with fresh coriander leaves.",
      "Serve the chicken curry hot with rice or naan bread.",
      "Enjoy your flavorful Chicken Curry!",
    ],
  },
  {
    recipeOwnerId: "user456",
    recipeNameId: "paneerMasala789",
    recipeName: "Paneer Butter Masala",
    ingredients: {
      Paneer: "250 gm, cubed",
      Onion: "2, finely chopped",
      Tomatoes: "3, pureed",
      "Ginger-GarlicPaste": "1 tbsp",
      CashewNuts: "10, soaked",
      Cream: "1/4 cup",
      KasuriMethi: "1 tsp",
      GaramMasala: "1 tsp",
      TurmericPowder: "1/2 tsp",
      RedChiliPowder: "1 tsp",
      Butter: "2 tbsp",
      Salt: "to taste",
      CorianderLeaves: "for garnish",
    },
    steps: [
      "Sauté chopped onions in butter until golden brown.",
      "Add ginger-garlic paste and sauté until the raw smell disappears.",
      "Add pureed tomatoes, cashew nuts, turmeric powder, red chili powder, and salt. Cook until the oil separates.",
      "Add cream, garam masala, kasuri methi, and cubed paneer. Simmer for 5 minutes.",
      "Garnish with coriander leaves and serve hot.",
    ],
  },
  {
    recipeOwnerId: "user789",
    recipeNameId: "vegetableBiryani987",
    recipeName: "Vegetable Biryani",
    ingredients: {
      BasmatiRice: "1 cup, soaked",
      MixedVegetables: "1 cup (carrots, peas, beans)",
      Onion: "1, thinly sliced",
      Tomatoes: "2, chopped",
      GingerGarlicPaste: "1 tbsp",
      BiryaniMasala: "2 tsp",
      CuminSeeds: "1 tsp",
      CinnamonStick: "1 inch",
      Cloves: "3",
      Cardamom: "2 pods",
      BayLeaves: "2",
      CashewNuts: "10",
      Ghee: "2 tbsp",
      CorianderLeaves: "for garnish",
      Salt: "to taste",
      Water: "2 cups",
    },
    steps: [
      "Heat ghee in a pan and add cumin seeds, cinnamon stick, cloves, cardamom, and bay leaves.",
      "Add sliced onions and sauté until golden brown.",
      "Add ginger-garlic paste and chopped tomatoes. Cook until tomatoes are soft.",
      "Add mixed vegetables, biryani masala, and soaked rice. Sauté for 2 minutes.",
      "Transfer the mixture to a rice cooker, add water, and cook until rice is done.",
      "Garnish with fried cashew nuts and coriander leaves. Serve hot.",
    ],
  },
  {
    recipeOwnerId: "user101",
    recipeNameId: "choleCurry112",
    recipeName: "Chole Curry",
    ingredients: {
      Chickpeas: "1 cup, soaked and boiled",
      Onion: "1, finely chopped",
      Tomatoes: "2, pureed",
      GingerGarlicPaste: "1 tbsp",
      CholeMasala: "2 tsp",
      CuminSeeds: "1 tsp",
      CorianderPowder: "1 tsp",
      TurmericPowder: "1/2 tsp",
      RedChiliPowder: "1 tsp",
      GaramMasala: "1/2 tsp",
      AmchurPowder: "1/2 tsp",
      CookingOil: "2 tbsp",
      CorianderLeaves: "for garnish",
      Salt: "to taste",
    },
    steps: [
      "Heat oil in a pan, add cumin seeds, and sauté chopped onions until golden brown.",
      "Add ginger-garlic paste and sauté until the raw smell disappears.",
      "Add pureed tomatoes, chole masala, coriander powder, turmeric powder, red chili powder, and salt. Cook until oil separates.",
      "Add boiled chickpeas and simmer for 10 minutes.",
      "Sprinkle garam masala, amchur powder, and garnish with coriander leaves.",
      "Serve hot with rice or naan.",
    ],
  },
  {
    recipeOwnerId: "user202",
    recipeNameId: "palakPaneer303",
    recipeName: "Palak Paneer",
    ingredients: {
      Paneer: "250 gm, cubed",
      Spinach: "2 cups, blanched and pureed",
      Onion: "1, finely chopped",
      Tomatoes: "2, chopped",
      "Ginger-GarlicPaste": "1 tbsp",
      CuminPowder: "1 tsp",
      CorianderPowder: "1 tsp",
      TurmericPowder: "1/2 tsp",
      RedChiliPowder: "1/2 tsp",
      GaramMasala: "1/2 tsp",
      CookingOil: "2 tbsp",
      Salt: "to taste",
      FreshCream: "2 tbsp",
      CorianderLeaves: "for garnish",
    },
    steps: [
      "Heat oil in a pan, add chopped onions and sauté until golden brown.",
      "Add ginger-garlic paste and sauté until the raw smell disappears.",
      "Add chopped tomatoes, cumin powder, coriander powder, turmeric powder, and red chili powder. Cook until tomatoes are soft.",
      "Add pureed spinach and cook for 5 minutes.",
      "Add paneer cubes, garam masala, salt, and fresh cream. Simmer for another 5 minutes.",
      "Garnish with coriander leaves and serve hot.",
    ],
  },
  {
    recipeOwnerId: "user404",
    recipeNameId: "alooGobi505",
    recipeName: "Aloo Gobi Curry",
    ingredients: {
      Potatoes: "2, peeled and cubed",
      Cauliflower: "1 small, cut into florets",
      Onion: "1, finely chopped",
      Tomatoes: "2, chopped",
      GingerGarlicPaste: "1 tbsp",
      CuminSeeds: "1 tsp",
      TurmericPowder: "1/2 tsp",
      CorianderPowder: "1 tsp",
      RedChiliPowder: "1/2 tsp",
      GaramMasala: "1/2 tsp",
      CookingOil: "2 tbsp",
      FreshCoriander: "for garnish",
      Salt: "to taste",
    },
    steps: [
      "Heat oil in a pan, add cumin seeds, and sauté chopped onions until golden brown.",
      "Add ginger-garlic paste and sauté until the raw smell disappears.",
      "Add chopped tomatoes, turmeric powder, coriander powder, red chili powder, and salt. Cook until tomatoes are soft.",
      "Add cubed potatoes and cauliflower florets. Mix well to coat with the spices.",
      "Cover and cook until the vegetables are tender. Sprinkle garam masala.",
      "Garnish with fresh coriander leaves and serve hot.",
    ],
  },
  {
    recipeOwnerId: "user606",
    recipeNameId: "dalTadka707",
    recipeName: "Dal Tadka",
    ingredients: {
      "YellowLentils (Toor Dal)": "1 cup, washed",
      Onion: "1, finely chopped",
      Tomatoes: "2, chopped",
      GreenChilies: "2, chopped",
      "Ginger-GarlicPaste": "1 tbsp",
      CuminSeeds: "1 tsp",
      MustardSeeds: "1/2 tsp",
      "Asafoetida (Hing)": "a pinch",
      TurmericPowder: "1/2 tsp",
      RedChiliPowder: "1/2 tsp",
      GaramMasala: "1/2 tsp",
      CurryLeaves: "a few",
      CookingOil: "2 tbsp",
      Salt: "to taste",
      FreshCoriander: "for garnish",
    },
    steps: [
      "Boil the lentils with turmeric powder and salt until soft. Mash them slightly.",
      "In a separate pan, heat oil, add cumin seeds, mustard seeds, hing, and curry leaves.",
      "Add chopped onions, green chilies, and ginger-garlic paste. Sauté until onions are golden brown.",
      "Add chopped tomatoes, red chili powder, and garam masala. Cook until tomatoes are soft.",
      "Mix the cooked lentils with the tempering mixture. Adjust the consistency by adding water if needed.",
      "Garnish with fresh coriander leaves and serve hot with rice or roti.",
    ],
  },
  {
    recipeOwnerId: "user808",
    recipeNameId: "masoorDal909",
    recipeName: "Masoor Dal Curry",
    ingredients: {
      "RedLentils (Masoor Dal)": "1 cup, washed",
      Onion: "1, finely chopped",
      Tomatoes: "2, chopped",
      "Ginger-GarlicPaste": "1 tbsp",
      CuminPowder: "1 tsp",
      CorianderPowder: "1 tsp",
      TurmericPowder: "1/2 tsp",
      RedChiliPowder: "1/2 tsp",
      GaramMasala: "1/2 tsp",
      MustardSeeds: "1/2 tsp",
      CurryLeaves: "a few",
      CookingOil: "2 tbsp",
      Salt: "to taste",
      FreshCoriander: "for garnish",
    },
    steps: [
      "Boil the red lentils with turmeric powder and salt until soft. Mash them slightly.",
      "In a pan, heat oil, add mustard seeds and curry leaves.",
      "Add chopped onions, ginger-garlic paste, and sauté until onions are translucent.",
      "Add chopped tomatoes, cumin powder, coriander powder, red chili powder, and salt. Cook until tomatoes are soft.",
      "Mix the cooked lentils with the tempering mixture. Simmer for 10 minutes.",
      "Sprinkle garam masala, garnish with fresh coriander leaves, and serve hot.",
    ],
  },
  {
    recipeOwnerId: "user999",
    recipeNameId: "tandooriChicken1010",
    recipeName: "Tandoori Chicken",
    ingredients: {
      Chicken: "500 gm, cut into pieces",
      Yogurt: "1/2 cup",
      "Ginger-GarlicPaste": "2 tbsp",
      RedChiliPowder: "1 tbsp",
      TurmericPowder: "1/2 tsp",
      GaramMasala: "1 tsp",
      LemonJuice: "2 tbsp",
      Salt: "to taste",
      CookingOil: "2 tbsp",
      TandooriMasala: "2 tbsp",
      FreshCoriander: "for garnish",
    },
    steps: [
      "In a bowl, mix yogurt, ginger-garlic paste, red chili powder, turmeric powder, garam masala, lemon juice, and salt to make the marinade.",
      "Marinate the chicken in the mixture and refrigerate for at least 2 hours.",
      "Preheat the oven to 200°C. Thread the chicken onto skewers.",
      "Brush with oil and sprinkle tandoori masala over the chicken.",
      "Bake for 25-30 minutes or until the chicken is fully cooked and has a charred appearance.",
      "Garnish with fresh coriander leaves and serve hot.",
    ],
  },
];

export default SampleRecipes;
